const
  GET_CITY_FORECAST = 'GET_CITY_FORECAST',
  SET_FORECAST_RESULT_TO_STORE = 'SET_FORECAST_RESULT_TO_STORE',
  SET_LOADING = 'SET_LOADING';

export default {
  SET_LOADING,
  GET_CITY_FORECAST,
  SET_FORECAST_RESULT_TO_STORE
};
